### ISSUE TITLE
Is there a version implemented using tf？

### ISSUE THREAD

**Issue by yanyanlimingkun** [StevenBanama/C3AE#21]
StevenBanama:
     I would like to ask you if there is a version that is simply implemented by tensorflow. Is not tf.keras used

**Comment by StevenBanama** [comment]
> StevenBanama:
> I would like to ask you if there is a version that is simply implemented by tensorflow. Is not tf.keras used

not yet!!  but it do not change a lot. This repos just design to validate C3AE
