### ISSUE TITLE
The current model has a poor effect on gray scale. Do you have any solutions

### ISSUE THREAD

**Issue by yanyanlimingkun** [StevenBanama/C3AE#22]
StevenBanama
    The current model has a poor effect on gray scale. Do you have any solutions？
    Looking forward to your reply

**Comment by StevenBanama** [comment]
> StevenBanama
> The current model has a poor effect on gray scale. Do you have any solutions？
> Looking forward to your reply

you'd better retrain in gray dataset. 
firstly change the dataset from rgb to gray and change the channel of Input, then retrain the model(remenber to remove "white norm").
