### ISSUE TITLE
about category and interval

### ISSUE THREAD

**Issue by QingMMao** [StevenBanama/C3AE#54]
In nets/utils.py function two_point, 
The interval is 10 but category is 12, 
If interval is 10，bins should be [0,10,20,30,40,50,60,70,80,90,100] length is 11, according to my understanding, 
But   embed's length is 12, 
I don't know why.

**Comment by StevenBanama** [comment]
you'd better print the categories,which may help you to understand it; only 10 bins in paper: why we got 12 category: we can split it as "[0, 10, ... 110 ]" by two points!

**Comment by QingMMao** [comment]
Thanks for your reply, and I understand that.
